config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # verb "url", to: "controller#action"
  # get "/tasks", to: "tasks#index"

  # CRUD
  # CREATE, READ, UPDATE, DELETE

  # Read all the tasks
  get "/tasks", to: "tasks#index"

  # Create a task
  # YOU MUST PUT THIS BEFORE read one task, because rails gets confused between 
  # /tasks/:id and /tasks/new
  get "/tasks/new", to: "tasks#new" # Display the form
  post "/tasks", to: "tasks#create"

  # Read one task
  get "/tasks/:id", to: "tasks#show", as: 'task'

  # Update a task
  get "/tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
  patch "/tasks/:id", to: "tasks#update"

  # Delete a task
  delete "/tasks/:id", to: "tasks#destroy"
end

# To change the prefix, especially today as you're not allowed to use resources :tasks, use as: 'task' on line 19.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action: find_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    # raise
    @task = Task.find(params[:id])
  end

  def new
    # This creates an empty instance of Task
    @task = Task.new
  end

  def create
    #  raise, put a raise here then go to http://localhost:3000/tasks/new, fill in the form then play around with params[:task]
    # @task = Task.new(params[:task])
    # task_params is an updated version of params[:task] which is more secure.
    @task = Task.new(task_params)
    @task.save
    # Also today it doesn't matter if you do Task.new task.save or Task.create
    # Tomorrow we'll do validations, if save? ... do this else re render the form.

    redirect_to tasks_path(@task)
    # The prefix to the show page is task, so we redirect to the task_path which is the show page of all the tasks.
    # We need (@task) because the show page has a :id in the url which is dynamic, so you pass it the instance of @task for the id.
    # By default @task will take the id, if you want something else, like title you have to do @task.title.
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
    # This is the path to the index page, check using rails routes in the terminal
  end

  private

  def task_params
    # Strong params - This says, only look at these fields, don't look at anything else.. e.g if a hacker came along and edited the html in
    # their browser to add another field to the form (permitted for example), whereby they could check the box permitted, and make their
    # new Task show up immediately without having to go through checks.
    params.require(:task).permit(:title, :details, :completed)
  end

  # def find_task
  # end
end

# @task = Task.find(params[:id]) is repeated loads.
# REFACTOR

# class TasksController < ApplicationController
#   before_action: find_task, only: [:show, :edit, :update, :destroy]

#   def index
#     @tasks = Task.all
#   end

#   def show; end

#   def new
#     @task = Task.new
#   end

#   def create
#     @task = Task.new(task_params)
#     @task.save
#     redirect_to tasks_path(@task)
#   end

#   def edit; end

#   def update
#     @task.update(task_params)
#     redirect_to tasks_path(@task)
#   end

#   def destroy
#     @task.destroy
#     redirect_to tasks_path
#   end

#   private

#   def task_params
#     params.require(:task).permit(:title, :details, :completed)
#   end

#   def find_task
#     @task = Task.find(params[:id])
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%# SIMPLE FORMS METHOD %>
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed, "Completed" %>
  <%= f.submit %>
<% end %>

<%# NORMAL METHOD %>
<%# <form action="/tasks" method="post">
  <%= hidden_field_tag :Authenticity_token, form_authenticity_token %>
  <%# <label for="title">Title</label>
  You want the information to be filled in when you're editing a task - this is what value is for %>
  <%# <input type="text" name="task[title]" value="Make Bed">
  <label for="details">Details</label>
  <input type="text" name ="task[details]" value="Put the sheets on">
   <label for=""></label>
  <input type="text">
  <input type="submit">
</form> %> 

app/views/tasks/index.html.erb
<h1 class="title">To Do List</h1>

<div class="list">
  <% @tasks.each do |task| %>
    <div class="items">
      <h5><%=  link_to task.title, task_path(task), class: "link-orange" %></h5>
      <p><%= task.details %></p>
    </div>
  <% end %>
</div>

<%= link_to 'Create a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<%# Form_for automatically generates your authenticity token for you %>
<h1 class="title">New Task</h1>

<%# SIMPLE FORMS METHOD %>
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<br>
<br>
<br>

<%# action is /tasks because if you check the routes %>
<%# post "/tasks", to: "tasks#create" %>
<%# <form action="/tasks" method="post"> %>
  <%# Inspect the form on browser and see that you get a super long token. The browser is going to match this token with the value in your session %>
  <%# If it matches that of your token, it will confirm that the form is being submitted from this website. %>
  <%# What's a form? Its a piece of information that goes from one page to another. %>
  <%# If I'm a hacker and I know my way around rails, I can go to my app and make a form that redirects to your form and push whatever data I want. %>
  <%# This token, I won't have access to it from your app so I won't be able to push something to your website. %>
  <%# Prevents CSRF attacks. google it. %>
  <%# <%= hidden_field_tag :Authenticity_token, form_authenticity_token %>
  <%# Title form %>
  <%# <label for="title">Title</label> %>
  <%# <input type="text" name="task[title]"> %>
  <%# Details form %>
  <%# <label for="details">Details</label>
  <input type="text" name ="task[details]">
   <label for=""></label>
  <input type="text"> %>
  <%# Submit button %>
  <%# <input type="submit">
</form> %>

<%# The reason name="task[fieldname]" is because if we want to create a task.... %>

<%# This is really long: %>
<%# Task.create(title: params[:title], details: [:details]) %>

<%# This is better: %>
<%# Task.create(params[:task]) %>

<%# So in our params we create a key 'task' and then the value is a hash with title, and details. %>

<%# params = {
      task: {
        title: 'Make Bed',
        details: 'Take the dirty linen off and put on new linen'
      }
    } %>

<%# so...              Task.create(params[:task])  %>
<%# is the same as ... Task.create(title: 'Make Bed', details: 'Take the dirty linen off and put on new linen') %>

app/views/tasks/show.html.erb
<h1 class="title"><%= @task.title %></h1>
<p>Description: <%= @task.details %></p>
<p>
  <% if !@task.completed %>
    This task is not completed yet
  <% else %>
    This task is completed
  <% end %>
</p>

<%= link_to 'Home', tasks_path %>
<%= link_to 'Edit', edit_task_path(@task) %>

<%# Need to specify that the method is delete otherwise its going to think you want the show page %>
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>

<%# <%= link_to 'delete', task_path(@task.id), method: :delete %>
<%# You can use @task.id it's the same as @task %>

app/views/tasks/task.html.erb
<h1>Tasks</h1>